config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  root to: "events#index"

  resources :users, only: [:show, :edit, :update]
  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user, dependent: :destroy
  has_many :photos, dependent: :destroy

  validates :title, presence: true, length: {maximum: 60}
  validates :address, presence: true, length: {maximum: 120}
  validates :description, length: {maximum: 300}
  validates :datetime, presence: true

  def visitors
    (subscribers + [user]).uniq
  end

  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:show]

  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_event, only: %i[show destroy edit]
  before_action :password_guard!, only: [:show]

  after_action :verify_authorized, except: [:index]

  def index
    @events = policy_scope(Event)
  end

  def show
    authorize @event

    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  end

  def new
    @event = current_user.events.build

    authorize @event
  end

  def create
    @event = current_user.events.build(event_params)

    authorize @event

    if @event.save
      redirect_to @event, notice: I18n.t("controllers.events.created")
    else
      render :new
    end
  end


  def edit
    authorize @event
  end

  def update
    authorize @event

    if @event.update(event_params)
      redirect_to @event, notice: I18n.t("controllers.events.updated")
    else
      render :edit
    end
  end

  def destroy
    authorize @event

    @event.destroy
    redirect_to root_path, notice: I18n.t("controllers.events.destroyed")
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
  end

  def password_guard!
    return true if @event.pincode.blank?
    return true if policy(@event).edit?

    if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
      cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
    end

    pincode = cookies.permanent["events_#{@event.id}_pincode"]
    unless @event.pincode_valid?(pincode)
      if params[:pincode].present?
        flash.now[:alert] = I18n.t("controllers.events.wrong_pincode")
      end
      render "pincode_form"
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="col-sm-6 col-md-4 my-2">
  <div class="thumbnail Regular shadow">
    <%= content_tag "div", "", class: "event-background",
      style: "background-image: url(#{event_photo(event)})" %>

    <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description">
          <h3 class="mx-3"><%= link_to event.title, event_path(event), data: { turbo: false } %></h3>
          <h3 class="mx-3"><small><%= l event.datetime, format: :long %></small></h3>
          <div class="buffer-both mx-3"><%= event.address %></div>
        </div>

        <div>
          <% event.visitors.each do |user| %>
            <%= image_tag user_avatar_thumb(user), class: "img-icon", title: user.name %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render partial: "partials/form_errors", locals: { model: @event } %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group mt-3">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group mt-3">
    <%= f.label :datetime %>
    <p><%= f.datetime_select :datetime, class: "form-control" %></p>
  </div>

  <div class="form-group mt-3">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group mt-3 col-4">
    <%= f.label :pincode %>
    <%= f.text_field :pincode, class: "form-control" %>
  </div>

  <div class="actions my-3">
    <%= f.submit t("views.buttons.create"), class: "btn btn-primary", data: { turbo: false } %>
    <%= t("views.buttons.or") %> <%= link_to t("views.buttons.back"), :back %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="row justify-content-center">
  <div class="col-8 buffer-bottom row bg-light rounded-5 px-5">  
    <h1 class="text-center"><%= t("views.event.edit") %></h1>

    <div class="row justify-content-center">
      <div class="col-md-6 buffer-top">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>  

app/views/events/index.html.erb
<div class="text-center">
  <h1>События</h1>

  <div class="buffer-both">
    <%= link_to t("views.event.create"), new_event_path, class: "btn btn-primary" %>
  </div>

  <div class="row buffer-bottom">
    <%= render partial: "events/event", collection: @events %>
  </div>
</div>

app/views/events/new.html.erb
<div class="row justify-content-center">
  <div class="col-8 buffer-bottom row bg-light rounded-5 px-5">  
    <h1 class="text-center"><%= t("views.event.create") %></h1>

    <div class="row justify-content-center">
      <div class="col-md-6 buffer-top">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>  

app/views/events/pincode_form.html.erb
<div class="row justify-content-center">
  <div class="bg-light col-lg-6 col-md-8 px-5 py-3 rounded-5">
    <h1><%= t("views.event.pincode") %></h1>

    <%= form_tag("", method: "post") do |f| %>
      <div class="form-group my-3 col-5">
        <i class="icon-key mx-1"></i>
        <%= text_field_tag :pincode, params[:pincode], class: "form-control my-3" %>
      </div>

      <div class="actions my-3">
        <%= submit_tag t("views.buttons.send"), class: "btn btn-primary", data: { turbo: false } %>
      </div>
    <% end %>

    <%= link_to t("views.buttons.back"), events_path %>
  </div>
</div>

app/views/events/show.html.erb
<div class="event">
  <div class="event-info row rounded-5">
    <div class="col-md-12">
      <%= content_tag "div", "", class: "event-background rounded-5",
        style: "background-image: url(#{event_photo(@event)})" %>

      <div class="event-info-inner row py-5 rounded-5 px-5">
        <div class="col-md-6">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :long %></h3>
            <h3>
              <small><%= link_to @event.address, "https://yandex.ru/maps/?text=#{@event.address}" %></small>
            </h3>
            <p><%= @event.description %></p>
          </div>

          <% if policy(@event).edit? %>
            <div class="buffer-both">
              <%= link_to t("views.buttons.edit"), edit_event_path(@event),
                class: "btn btn-primary" %>
            </div>

            <div class="buffer-both">
              <%= button_to t("views.buttons.delete"), event_path(@event), method: :delete, data: { turbo_confirm: t("confirmation.messages.event") }, class: "btn btn-danger" %>
            </div>
          <% end %>
        </div>
       
        <div class="col-md-6">
          <div id="map" class="text-dark"
            data-address= '<%= @event.address %>'
            style="width: 100%; height: 400px;">
          </div>  
        </div>
        
      </div>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-lg-7 mx-1">
      <div class="event-photos-gallery">
        <div class="buffer-bottom row bg-light rounded-5 px-5">
          <div class="col-md-10">
            <div class="event-photo buffer-both row">
              <% if @event.photos.except(@new_photo).count == 0 %>
                <h3><%= t("views.event.photos") %></h3>
              <% else %>
                <% @event.photos.except(@new_photo).each_with_index do |photo, index| %>
                  <%= render partial: "photos/photo", locals: { photo: photo, index: index } %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>

      </div>
      
      <% if policy(@new_photo).create? %>
        <div class="event-photo-form">
          <%= render partial: 'photos/form', locals: { photo: @new_photo || @event.photos.build } %>
        </div>
      <% end %>

      <div class="event-comments buffer-top">
        <% if policy(@new_comment).create? %>
          <%= render partial: "comments/form",
            locals: { comment: @new_comment || @event.comments.build } %>
        <% end %>

        <div class="buffer-both">
          <%= render partial: "comments/comment",
            collection: @event.comments.except(@new_comment) %>
        </div>
      </div>
    </div>

    <div class="col-lg-4">
      <div class=" mx-3 mt-3 rounded-5 bg-light py-3 px-3">
        <div class="event-owner">
          <h4 class="mt-3"><%= t("views.event.calling") %></h4>
            <p><%= render partial: 'users/user', object: @event.user %></p>
        </div>

        <% unless @event.subscriptions.count == 0 %>
          <div class="event-subscriptions">
            <h4><%= t("views.event.will_go") %></h4>
            <div>
              <p>
              <%= render partial: "subscriptions/subscription",
                collection: @event.subscriptions.except(@new_subscription) %>
              </p>
            </div>
          </div>
        <% end %>

        <% if policy(@new_subscription).create? %>
          <div class="event-subscription-form">
            <h4><%= t("views.event.i_will_go") %></h4>
            <div>
              <%= render partial: "subscriptions/form", locals: { subscription: @new_subscription || @event.subscriptions.build } %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>